version: '3.7'

services:
  app:
    container_name: app
    image: app
    depends_on:
      - app_db
    env_file:
      - .env
    ports:
      - "80:8000"
    build:
      context: .
      dockerfile: Dockerfile.prod
    command:
      - entrypoints/gunicorn.sh
    networks:
      - mynetwork
  
  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - app_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  app_db_data:

