"""more booking changes

Revision ID: 5865045e629f
Revises: 98adfe081891
Create Date: 2024-06-26 07:30:17.251152

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5865045e629f"
down_revision = "98adfe081891"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking", sa.Column("timezone", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking", "timezone")
    # ### end Alembic commands ###
