"""booking model

Revision ID: 1ad8eeee2681
Revises: 76bdbce911d9
Create Date: 2024-06-25 21:16:29.049196

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1ad8eeee2681"
down_revision = "76bdbce911d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("spot", sa.DateTime(), nullable=False),
        sa.Column("booked_by_id", sa.String(), nullable=False),
        sa.Column("booked_for_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booked_by_id"], ["user.id"], name=op.f("booking_booked_by_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["booked_for_id"], ["user.id"], name=op.f("booking_booked_for_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("booking_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("booking")
    # ### end Alembic commands ###
