"""more models

Revision ID: e75ff431a8f2
Revises: 80356775cc1e
Create Date: 2024-06-24 10:16:33.966472

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e75ff431a8f2"
down_revision = "80356775cc1e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("availability_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("availability_pkey")),
    )
    op.create_table(
        "event",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("availability_id", sa.String(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("starts_from", sa.Date(), nullable=False),
        sa.Column("ends_at", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["availability_id"],
            ["availability.id"],
            name=op.f("event_availability_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("event_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    op.drop_table("availability")
    # ### end Alembic commands ###
