"""event description

Revision ID: 71313c4fcb2f
Revises: 5865045e629f
Create Date: 2024-06-26 12:38:08.799934

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "71313c4fcb2f"
down_revision = "5865045e629f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("description", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "description")
    # ### end Alembic commands ###
