"""availablility model changes

Revision ID: 76bdbce911d9
Revises: e75ff431a8f2
Create Date: 2024-06-24 15:57:30.252522

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "76bdbce911d9"
down_revision = "e75ff431a8f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("availability", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("availability", "name")
    # ### end Alembic commands ###
